language: python

python:
    - "2.7_with_system_site_packages"

virtualenv:
    system_site_packages: true

# Setup anaconda
before_install:
    - sudo apt-get update
    - sudo apt-get install -qq python2-numpy python2-scipy

# Install packages
install:
    - python setup.py install

script: "python test_runner.py"
