language: python

python:
    - "2.7"

virtualenv:
    system_site_packages: true

before_install:
    - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
    - apt-get install python2-numpy
    - apt-get install python2-scipy

install:
  - python setup.py install

script: "python test_runner.py"
