language: python

python:
    - "2.7"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install libblas-dev
    - sudo apt-get install liblapack-dev
    - sudo apt-get install gfortran

# Install packages
install:
    - pip install scipy
    - pip install numpy
    - pip install matplotlib
    - pip install pandas
    - pip install python-coveralls
    - pip install coverage
    - pip install nose
    - python setup.py install

script:
    - nosetests --with-coverage

after_success:
    - coveralls
