language: python

python:
    - "2.7"

# Install packages
install:
    - pip install scipy
    - pip install numpy
    - pip install matplotlib
    - pip install pandas
    - python setup.py install

script: "python test_runner.py"
